crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from stark.service.v1 import site
from web.views import account


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^stark/', site.urls),
    url(r'^rbac/', include(('rbac.urls', 'rbac'), namespace='rbac')),

    # 用户
    url(r'^login/', account.login, name='login'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'^index/', account.index, name='index'),
]

rbac/service/urls.py
# create: '2019/1/18' - 362416272@qq.com
from django.urls import reverse
from django.http import QueryDict  # 转义 会把等于号转为"%3D"


def memory_url(request, name, *args, **kwargs):  # *后面还可以传递本身就有的get参数
    """
    生产带有原条件的url
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)  # 反向生成args指，原搜索条件带进去
    if not request.GET:
        return basic_url
    else:
        old = request.GET.urlencode()  # 取 所有参数 ？号后面的
        # 加上前缀 比如？_filter+old 将参数打包 注意old必须要带上引号【转义】

        query_dict = QueryDict(mutable=True)
        query_dict['_filter'] = request.GET.urlencode()  # 这个类自动打包转义（之前的所有get参数）

        return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL【把原来的urlGET参数获取并生成在新页面】
        例如：  /rbac/menu/add?_filter=mid%3D2
        1. 在url总将原来的搜索条件，如_filter后的值
        2. reverse生成原来的URL， 如 /menu/list/
        3. /menu/list/?mid=%3D2
    :return:
    """
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')  # 取参数
    if origin_params:  # 如果有原始的get参数
        url = '%s?%s' % (url, origin_params)
    return url

rbac/urls.py
# create: '2018/12/13' - 362416272@qq.com  
from django.conf.urls import url
from django.urls import path
from rbac.views import role
from rbac.views import user
from rbac.views import menu

urlpatterns = [
    # 角色管理
    # 加上name可以让html动态反向获取url！！ 因为上级urls中有namespace=rbac语法{% url 'rbac:role_list' %}
    path('role/list/', role.role_list, name='role_list'),
    path('role/add/', role.role_add, name='role_add'),
    url(r'^role/edit/(?P<pk>\d+)/$', role.role_edit, name='role_edit'),  # {% url 'rbac:role_edit' %}
    url(r'^role/del/(?P<pk>\d+)/$', role.role_del, name='role_del'),  # {% url 'rbac:role_edit' %}

    # 用户管理
    # path('user/list/', user.user_list, name='user_list'),
    # path('user/add/', user.user_add, name='user_add'),
    # url(r'^user/edit/(?P<pk>\d+)/$', user.user_edit, name='user_edit'),  # {% url 'rbac:user_edit' %}
    # url(r'^user/del/(?P<pk>\d+)/$', user.user_del, name='user_del'),  # {% url 'rbac:user_edit' %}
    # url(r'^user/reset/password/(?P<pk>\d+)/$', user.user_reset_pwd, name='user_reset_pwd'),  # {% url 'rbac:user_edit' %}


    # 权限分配菜单（一级菜单）
    path('menu/list/', menu.menu_list, name='menu_list'),
    path('menu/add/', menu.menu_add, name='menu_add'),
    url(r'^menu/edit/(?P<pk>\d+)/$', menu.menu_edit, name='menu_edit'),
    url(r'^menu/del/(?P<pk>\d+)/$', menu.menu_del, name='menu_del'),

    # 二级菜单
    url(r'^second/menu/add/(?P<menu_id>\d+)/$', menu.second_menu_add, name='second_menu_add'),
    url(r'^second/menu/edit/(?P<pk>\d+)/$', menu.second_menu_edit, name='second_menu_edit'),
    url(r'^second/menu/del/(?P<pk>\d+)/$', menu.second_menu_del, name='second_menu_del'),

    # 权限 三级菜单
    url(r'^permission/add/(?P<second_menu_id>\d+)/$', menu.permission_add, name='permission_add'),
    url(r'^permission/edit/(?P<pk>\d+)/$', menu.permission_edit, name='permission_edit'),
    url(r'^permission/del/(?P<pk>\d+)/$', menu.permission_del, name='permission_del'),

    # 批量添加、编辑权限
    path('multi/permissions/', menu.multi_permissions, name='multi_permissions'),
    url(r'^multi/permissions/del/(?P<pk>\d+)/$', menu.multi_permissions_del, name='multi_permissions_del'),

    # 权限分配
    path('distribute/permissions/', menu.distribute_permissions, name='distribute_permissions'),
]

rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    一级菜单表
    """
    title = models.CharField(verbose_name='菜单名称', max_length=32)
    # 图标http://fontawesome.dashgame.com/
    icon = models.CharField(verbose_name='菜单图标', max_length=32)  # blank 为admin后台可以空

    def __str__(self):
        return self.title


class Permission(models.Model):
    """
    权限表
    """
    title = models.CharField(verbose_name='标题', max_length=32)
    url = models.CharField(verbose_name='含正则的URL', max_length=128)
    # 用来做控制，一些小权限（非菜单）么有就不显示
    name = models.CharField(verbose_name='URL别名', max_length=32, unique=True)  # unique唯一
    menu = models.ForeignKey(verbose_name='所属一级菜单', help_text='null表示不是菜单，否则为二级菜单', null=True, blank=True, to='Menu',
                             on_delete=models.CASCADE)

    # 跟自身表关联，已经是菜单的就可以不关联null=True
    # 非菜单的权限，要选一个母菜单。当选中该权限时就可以归类跳转到母菜单下
    pid = models.ForeignKey(verbose_name='关联的权限', to='Permission', null=True, blank=True, related_name='parents',
                            help_text='非菜单的权限，要选一个母菜单。当选中该权限时就可以归类跳转到母菜单下', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '权限表'
        verbose_name_plural = verbose_name


class Role(models.Model):
    """
    角色
    """
    title = models.CharField(verbose_name='角色名称', max_length=32)
    permissions = models.ManyToManyField(verbose_name='拥有的所有权限', to='Permission', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '角色'
        verbose_name_plural = verbose_name


class UserInfo(models.Model):
    """
    用户表
    """
    name = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    email = models.CharField(verbose_name='邮箱', max_length=32)
    roles = models.ManyToManyField(verbose_name='拥有的所有角色', to=Role, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        # 此类可以当做父类，被其他model继承。字段自动过度给，继承的model
        abstract = True  # 【django以后做数据库迁移时， 不再为UserInfo类创建相关的表以及表结构了】
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

rbac/forms/base.py
# create: '2019/1/19' - 362416272@qq.com
from django import forms


class BootStrapModelForm(forms.ModelForm):
    """统一给modelform生成字段添加boot样式"""
    def __init__(self, *args, **kwargs):
        super(BootStrapModelForm, self).__init__(*args, **kwargs)
        # 统一给modelform生成字段添加boot样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

rbac/forms/role.py
# create: '2018/12/14' - 362416272@qq.com  
from django import forms
from rbac import models


class RoleModelForm(forms.ModelForm):
    """ModelForm自动渲染form的类，便于下面调用"""
    class Meta:
        model = models.Role
        fields = ['title', ]

        # 调用bootCSS  给加上class=''即可  自定义样式！
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }

rbac/forms/user.py
# create: '2018/12/14' - 362416272@qq.com  
from django.core.exceptions import ValidationError

from django import forms
from rbac import models


class UserModelForm(forms.ModelForm):
    """ModelForm自动渲染form的类，便于下面调用"""
    # 第二次密码确认！！自定义一个字段
    confirm_password = forms.CharField(label='确认密码')

    class Meta:

        model = models.UserInfo
        fields = ['name', 'email', 'password', 'confirm_password']

        # 调用bootCSS  给加上class=''即可  自定义样式！
        # widgets = {
        #     'name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'email': forms.TextInput(attrs={'class': 'form-control'}),
        #     'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        #     'confirm_password': forms.PasswordsInput(attrs={'class': 'form-control'}),
        # }

    def __init__(self, *args, **kwargs):
        """高效统一添加样式"""
        super(UserModelForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    # 钩子方法，做密码确认验证
    def clean_confirm_password(self):
        """检测密码是否一致"""
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            # 固定语法：抛出异常
            raise ValidationError('两次输入不一致')


class UpdateUserModelForm(forms.ModelForm):
    """修改用户信息表单（没有密码和确认密码）"""

    class Meta:
        model = models.UserInfo
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        """高效统一添加样式"""
        super(UpdateUserModelForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ResetPasswordUserModelForm(forms.ModelForm):
    """修改用户信息表单（没有密码和确认密码）"""
    # 第二次密码确认！！自定义一个字段
    confirm_password = forms.CharField(label='确认密码')

    class Meta:
        model = models.UserInfo
        fields = ['password', 'confirm_password']

    def __init__(self, *args, **kwargs):
        """高效统一添加样式"""
        super(ResetPasswordUserModelForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    # 钩子方法，做密码确认验证
    def clean_confirm_password(self):
        """检测密码是否一致"""
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            # 固定语法：抛出异常
            raise ValidationError('两次输入不一致')

rbac/service/routes.py
# create: '2019/1/23' - 362416272@qq.com

import re

from collections import OrderedDict  # 有序字典
from django.conf import settings
from django.utils.module_loading import import_string  # 把字符串导入模块

from django.urls import URLResolver, URLPattern  # url文件中urlpatterns数组中,URLResolver=继续往下走还有分发，URLPattern=没有分发


def check_url_exclude(url):
    """定制~：自动收录路由，白名单"""
    # 通常情况下 admin这些路由不需要收录
    exclude_url = settings.AUTO_DISCOVER_EXCLUDE
    for regex in exclude_url:
        if re.match(regex, url):
            return True


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    递归的去获取URL
    :param pre_namespace: namespace的别名前缀，以后用于拼接name 【namespace是分发的别名， name是路由的别名】
    :param pre_url:URL的地址前缀，以后用于拼接url
    :param urlpatterns:路由关系列表
    :param url_ordered_dict:用于保存递归获取到的所有路由
    :return:
    """
    for item in urlpatterns:
        route = ''
        # django2 后有了路由path 和 re_path更为方便，但两者的pattern不同（可以参考源码）所以要判断
        # 取当前层的路径route
        if item.pattern.__class__.__name__ == 'RoutePattern':  # 判断类名是不是RoutePattern
            route = item.pattern._route
        elif item.pattern.__class__.__name__ == 'RegexPattern':
            route = item.pattern._regex
        if isinstance(item, URLPattern):  # 没有分发,将路由添加到字典中
            if not item.name:
                continue  # 如果没有设置别名name就不管他，因为必须设置！！
            if pre_namespace:
                # 判断别名是否有前缀（不是一级分发） 比如'rbac:xxxx'
                name = "%s:%s" % (pre_namespace, item.name)
            else:
                name = item.name
            url = pre_url + route  # pre_url是前缀，后面是当前项的url路径
            url = url.replace('^', '').replace('$', '')
            '''过滤掉白名单的，比如admin不需要收录'''
            if check_url_exclude(url):
                continue
            url_ordered_dict[name] = {'name': name, 'url': url}
        elif isinstance(item, URLResolver):
            # 还有分发，继续递归自己
            if pre_namespace:  # 如果有前缀，别名要拼接
                if item.namespace:  # 还要判断自身是否有namespace
                    namespace = "%s:%s" % (pre_namespace, item.namespace)
                else:
                    # 如果自己没有namespace就用父级的
                    namespace = item.namespace
            else:
                if item.namespace:  # 如果自身有namespace，就用自身的
                    namespace = item.namespace
                else:
                    # 父级没有，自己也没有
                    namespace = None
            use_url = pre_url + route  # 上级的前缀url+ 自己的前缀
            recursion_urls(namespace, use_url, item.url_patterns, url_ordered_dict)


def get_all_url_dict():
    """
    获取项目中所有URL(有序字典)【*********必须要给url设置别名Name且唯一*********】
    :return:
    """
    url_ordered_dict = OrderedDict()
    '''等同于 from luff.. import urls'''
    md = import_string(settings.ROOT_URLCONF)  # 取根路由路径（setting中配置的）,再以字符串形式导入包
    recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)  # 递归获取所有路由，一级没有前缀所以=None 而且加上/
    return url_ordered_dict

rbac/views/role.py
# create: '2018/12/13' - 362416272@qq.com  
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse  # 根据name反向生成url比较实用

from rbac.forms.role import RoleModelForm
from rbac import models


def role_list(request):
    """角色列表"""
    role_queryset = models.Role.objects.all()

    return render(request, 'rbac/role_list.html', {'roles': role_queryset})


def role_add(request):
    """添加角色"""
    if request.method == 'GET':
        form = RoleModelForm()
        return render(request, 'rbac/change.html', {'form': form})
    form = RoleModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))  # 根据
    else:
        # 如果提交空数据
        return render(request, 'rbac/change.html', {'form': form})


def role_edit(request, pk):
    """修改角色"""
    obj = models.Role.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')
    if request.method == 'GET':
        form = RoleModelForm(instance=obj)  # instance=obj编辑页面带默认值
        return render(request, 'rbac/change.html', {'form': form, 'pk': pk})

    # POST
    form = RoleModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))  # 反向获取

    # 数据错误展示
    return render(request, 'rbac/change.html', {'form': form, 'pk': pk})


def role_del(request, pk):
    """删除角色"""
    origin_url = reverse('rbac:role_list')  # 反向取跳转链接
    if request.method == "GET":
        return render(request,'rbac/delete.html', {'cancel_url': origin_url})  # cancel_url是取消删除会跳地址

    # 确认删除
    models.Role.objects.filter(id=pk).delete()
    return redirect(origin_url)

rbac/views/user.py
# create: '2018/12/13' - 362416272@qq.com
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse  # 根据name反向生成url比较实用

from rbac.forms.user import *
from rbac.models import UserInfo


def user_list(request):
    """用户列表"""
    user_queryset = UserInfo.objects.all()

    return render(request, 'rbac/user_list.html', {'users': user_queryset})


def user_add(request):
    """添加用户"""
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'rbac/change.html', {'form': form})
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))  # 根据
    else:
        # 如果提交空数据
        return render(request, 'rbac/change.html', {'form': form})


def user_edit(request, pk):
    """修改用户"""
    obj = UserInfo.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')
    if request.method == 'GET':
        form = UpdateUserModelForm(instance=obj)  # instance=obj编辑页面带默认值
        return render(request, 'rbac/change.html', {'form': form, 'pk': pk})

    # POST
    form = UpdateUserModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))  # 反向获取

    # 数据错误展示
    return render(request, 'rbac/change.html', {'form': form, 'pk': pk})


def user_del(request, pk):
    """删除用户"""
    origin_url = reverse('rbac:user_list')  # 反向取跳转链接
    if request.method == "GET":
        return render(request, 'rbac/delete.html', {'cancel_url': origin_url})  # cancel_url是取消删除会跳地址

    # 确认删除
    UserInfo.objects.filter(id=pk).delete()
    return redirect(origin_url)


def user_reset_pwd(request, pk):
    """重置密码"""
    obj = UserInfo.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('角色不存在')
    if request.method == 'GET':
        form = ResetPasswordUserModelForm()
        return render(request, 'rbac/change.html', {'form': form, 'pk': pk})

    # POST
    form = ResetPasswordUserModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))  # 反向获取

    # 数据错误展示
    return render(request, 'rbac/change.html', {'form': form, 'pk': pk})

rbac/templates/rbac/breadcrumb.html
<!--用户访问路径追踪-->
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in record_list %}
            <!--判断是否是最后一层路径，最后一层为不可选中-->
            {% if item.class %}
                <li class="{{ item.class }}">{{ item.title }}</li>
            {% else %}
                <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

rbac/templates/rbac/change.html
{% extends 'layout.html' %}
{% block css %}
<style>
ul{
    list-style-type: none;
    padding: 0;
}
ul li{
    float:left;
    padding: 10px;
    padding-left: 0;
    width: 80px;
}
#id_icon li i{
    font-size: 18px;
    margin-left: 5px;
    color: #6d6565;
}
</style>
{% endblock %}
{% block content %}
<div class="luffy-container">
    <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input type="submit" value="保 存" class="btn btn-primary">
            </div>
        </div>
    </form>
</div>
{% endblock %}

rbac/templates/rbac/delete.html
<!--通用的新增和修改页面-->
{% extends 'layout.html' %}


{% block content %}

    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i>删除后不可恢复，请确认是否删除</p>


                <div style="margin-top: 20px;">
                    <a href="{{ cancel_url }}" class="btn btn-default btn-sm">取 消</a>
                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">

                </div>

            </form>
        </div>
    </div>


{% endblock %}

rbac/templates/rbac/multi_menu.html
<!--二级菜单-->

<div class="multi-menu">
    {% for item in menu_dict.values %}
        <div class="item">
            <div class="title"><span class="icon-wrap" style="margin-left: 10px;font-size: 16px;"><i class="{{ item.icon }}"></i></span> &nbsp;{{ item.title }}</div>
            <div class="body  {{ item.class }}">
                {% for per in item.children %}
                    <a class="{{ per.class }}" href="{{ per.url }}"  style="height: 40px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ per.title }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
<div class="luffy-container">
    <!--待添加的-->
    <form action="?type=generate" method="post"><!--提交地址generate-->
        {% csrf_token %}
        {{ generate_formset.management_form }}
        <div class="panel panel-default">
        <div class="panel-heading" style='font-weight: bold'>
            <i class="fa fa-list" aria-hidden="true"></i> 待新建权限列表
            <button class="right btn btn-primary btn-xs" style="">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                新建
            </button>
        </div>
        <div class="panel-body" style="color: #9d9d9d">
            注意：路由系统中自动发现且数据库中不存在的路由。
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>所属菜单</th>
                    <th>父权限</th>
                </tr>
            </thead>
            <tbody>
                {% for form in generate_formset %}
                    <tr>
                        <td style="">{{ forloop.counter }}</td>
                    {% for field in form %}
                        <td>
                            {{ field }}<span style="color:red;">{{ field.errors.0 }}</span>
                        </td>
                    {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </form>
    <!--待删除的-->
    <div class="panel panel-default">
        <div class="panel-heading" style='font-weight: bold'>
            <i class="fa fa-cubes" aria-hidden="true"></i> 数据库中有But路由没有
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>删除</th>
                </tr>
            </thead>
            <tbody>
                {% for row in delete_row_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ row.title }}</td>
                        <td>{{ row.url }}</td>
                        <td>{{ row.name }}</td>
                        <td>
                            <a href="{% url 'rbac:multi_permissions_del' pk=row.id %}" style="color: #d9534f;"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!--待更新的-->
    <form action="?type=update" method="post"><!--提交地址update-->
        {% csrf_token %}
        {{ update_formset.management_form }}
        <div class="panel panel-default">
        <div class="panel-heading" style='font-weight: bold'>
            <i class="fa fa-refresh" aria-hidden="true"></i> 待更新的权限表
            <button class="right btn btn-primary btn-xs" style="">
                <i class="fa fa-undo" aria-hidden="true"></i>
                更新
            </button>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>所属菜单</th>
                    <th>父权限</th>
                </tr>
            </thead>
            <tbody>
                {% for form in update_formset %}
                    <tr>
                        <td style="">{{ forloop.counter }}</td>
                        {% for field in form %}
                            {% if forloop.first %}
                                {{ field }}
                            {% else %}
                                <td>{{ field }}<span style="color:red;">{{ field.errors.0 }}</span></td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </form>
</div>
{% endblock %}

rbac/templates/rbac/role_list.html
<!--通用的新增和修改页面-->
{% extends 'layout.html' %}


{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <!--因为rbac的urls有上级urls所以 ，反向生成url的方法如下-->
            <a class="btn btn-default" href="{% url 'rbac:role_add' %}">  <!--反向生成url-->
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>


        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>选项</th>


            </tr>
            </thead>
            <tbody>
            {% for row in roles %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:role_edit' pk=row.id %}">  <!--反向取url 带参数pk-->
                            <i class="fa fa-edit" aria-hidden="true"></i></a>

                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' pk=row.id %}"><i
                                class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

rbac/templates/rbac/user_list.html
<!--通用的新增和修改页面-->
{% extends 'layout.html' %}


{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <!--因为rbac的urls有上级urls所以 ，反向生成url的方法如下-->
            <a class="btn btn-default" href="{% url 'rbac:user_add' %}">  <!--反向生成url-->
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加用户
            </a>


        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>密码操作</th>
                <th>操作</th>

            </tr>
            </thead>
            <tbody>
            {% for row in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    <td><a href="{% url 'rbac:user_reset_pwd' pk=row.id %}">重置密码</a></td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:user_edit' pk=row.id %}">  <!--反向取url 带参数pk-->
                            <i class="fa fa-edit" aria-hidden="true"></i></a>

                        <a style="color: #d9534f;" href="{% url 'rbac:user_del' pk=row.id %}"><i
                                class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}